#!/usr/bin/env node
// build-lexicon.mjs — lexicon-src/*.txt -> lexicon.v1.json (escape + validate). SPEC B.8.
//
// Turkish rows are folded with toLocaleLowerCase('tr') here, ONCE, so that matching never has to
// guess a locale; and every non-ASCII code point in the output is written as \uXXXX, because
// bidi-unaware editors and diff viewers reorder non-Latin literals and a maintainer "fixing" a
// reordered line silently corrupts the lexicon.
//
// Usage: node build-lexicon.mjs [--check]     (--check = fail if lexicon.v1.json is stale)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { caseFold, unifyApostrophe } from './lib/unicode.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'lexicon-src');
const OUT = join(HERE, 'lexicon.v1.json');

const FILES = [
  { file: 'en.txt', lang: 'en', kind: 'llm' },
  { file: 'tr.txt', lang: 'tr', kind: 'llm' },
  { file: 'human-en.txt', lang: 'en', kind: 'human' },
  { file: 'human-tr.txt', lang: 'tr', kind: 'human' },
];

const VALID_TAGS = new Set(['strong', 'weak']);
const VALID_DOMAINS = new Set(['general', 'cs', 'travel', 'email', 'marketing', 'essay', 'content', 'formal', 'tech']);
const VALID_FLAGS = new Set(['initial']);

function parseFile(path, lang, kind, errors) {
  const rows = [];
  const text = readFileSync(path, 'utf8');
  text.split(/\r?\n/).forEach((line, n) => {
    const t = line.trim();
    if (t === '' || t.startsWith('#')) return;
    const parts = line.split('|').map((p) => p.trim());
    if (parts.length < 2) { errors.push(`${path}:${n + 1}: need at least "phrase | tag"`); return; }
    const [rawPhrase, tag] = parts;
    const domain = parts[2] && parts[2] !== '-' ? parts[2] : 'general';
    const flags = parts[3] && parts[3] !== '-' ? parts[3].split(',').map((s) => s.trim()).filter(Boolean) : [];
    const note = parts[4] ?? '';
    if (!VALID_TAGS.has(tag)) { errors.push(`${path}:${n + 1}: bad tag "${tag}"`); return; }
    if (!VALID_DOMAINS.has(domain)) { errors.push(`${path}:${n + 1}: bad domain "${domain}"`); return; }
    for (const f of flags) if (!VALID_FLAGS.has(f)) errors.push(`${path}:${n + 1}: bad flag "${f}"`);
    // fold exactly as lib/unicode.mjs folds the text view, so matching is a plain string compare
    const phrase = caseFold(unifyApostrophe(rawPhrase.normalize('NFC')), lang);
    if (phrase.length < 1) { errors.push(`${path}:${n + 1}: empty phrase`); return; }
    if (note === '') errors.push(`${path}:${n + 1}: every row needs a confounder note (SPEC B.0)`);
    rows.push({ phrase, lang, kind, tag, domain, flags, note, source: rawPhrase });
  });
  return rows;
}

/** JSON with every non-ASCII code point written as \uXXXX. */
function escapeNonAscii(json) {
  return json.replace(/[\u0080-\uFFFF]/g, (c) => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
}

function main() {
  const errors = [];
  let rows = [];
  for (const f of FILES) {
    const p = join(SRC, f.file);
    if (!existsSync(p)) { errors.push(`missing ${p}`); continue; }
    rows = rows.concat(parseFile(p, f.lang, f.kind, errors));
  }

  // D-01: a bare Latin capital I tr-folds to the DOTLESS i, so "Inşallah geliriz" folds to
  // "ınşallah geliriz" and misses the row stored as "inşallah". The writer who types a bare I
  // where Turkish wants İ is precisely the writer this lexicon has to see (SPEC B.4 "in either
  // orthography"; features.mjs already carries both forms in TR_CITY). Emit the dotless-i variant
  // of every tr row that starts with i.
  const existing = new Set(rows.map((r) => `${r.lang} ${r.kind} ${r.phrase}`));
  const variants = [];
  for (const r of rows) {
    if (r.lang !== 'tr' || !r.phrase.startsWith('i')) continue;
    const phrase = 'ı' + r.phrase.slice(1);
    const key = `${r.lang} ${r.kind} ${phrase}`;
    if (existing.has(key)) continue;
    existing.add(key);
    variants.push({ ...r, phrase, note: r.note + ' [dotless-i orthography variant of "'
      + r.phrase + '", generated by build-lexicon.mjs: a bare Latin I folds to the dotless i]' });
  }
  rows = rows.concat(variants);

  const seen = new Map();
  for (const r of rows) {
    const key = `${r.lang} ${r.kind} ${r.phrase}`;
    if (seen.has(key)) errors.push(`duplicate phrase in ${r.lang}/${r.kind}: "${r.source}"`);
    seen.set(key, r);
  }

  if (errors.length) {
    for (const e of errors) console.error('ERROR ' + e);
    process.exit(1);
  }

  // Deterministic order: lang, kind, then phrase by code point. Never locale-compare here.
  rows.sort((a, b) => (a.lang < b.lang ? -1 : a.lang > b.lang ? 1
    : a.kind < b.kind ? -1 : a.kind > b.kind ? 1
      : a.phrase < b.phrase ? -1 : a.phrase > b.phrase ? 1 : 0));

  const payload = {
    version: 'v1',
    generatedBy: 'build-lexicon.mjs',
    note: 'Non-ASCII stored as \\uXXXX escapes on purpose (SPEC B.8). Edit lexicon-src/*.txt, not this file.',
    scope: 'en+tr (Arabic out of scope, HEAD-RULINGS R22)',
    counts: rows.reduce((acc, r) => { const k = `${r.lang}:${r.kind}`; acc[k] = (acc[k] ?? 0) + 1; return acc; }, {}),
    rows: rows.map(({ phrase, lang, kind, tag, domain, flags, note }) => ({ phrase, lang, kind, tag, domain, flags, note })),
  };

  const json = escapeNonAscii(JSON.stringify(payload, null, 2)) + '\n';

  if (process.argv.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (cur !== json) { console.error('STALE: lexicon.v1.json does not match lexicon-src/. Run: node build-lexicon.mjs'); process.exit(1); }
    console.log('lexicon.v1.json is up to date (' + rows.length + ' rows)');
    return;
  }

  writeFileSync(OUT, json);
  console.log('wrote lexicon.v1.json:', JSON.stringify(payload.counts), '=', rows.length, 'rows');
}

main();
